### ISSUE TITLE
Scaling of the SVGs in the top badges

### ISSUE THREAD

**Issue by luc-ass** [Bootstrap-Stage/Admin-LTE#1]
Hey there!

I recognized, that the background glyph somehow akwardly scales to down and to the left. I was able to fix this easily within the css and also added a (option) little fadeout. I have no idea if this should be changed within Admin-LTE or if this needs to be changed within the actual template.

from:
```css
.small-box:hover .icon {
    font-size: 95px;
}
```
to:
```css
.small-box:hover .icon {
    font-size: 95px;
    top: -14px;
    right: 7px;
    color: rgba(0,0,0,0.1)
}
```

Please let me know how you like it and wether to implement it.
